assignment 3 documentation for google search API
ayushttiwari/node-assignments-training pull request #2
Opened 2017-06-09 16:37 UTC by ayushttiwari

2017-06-12 12:58 UTC, devanshutechracers commented on swagger.yaml
> +      - name: "q"
is q a `query` parameter? And if it is why is it in body as well. Do u REALLY get it what are `query` and `body` parameters?

2017-06-12 13:04 UTC, devanshutechracers commented on swagger.yaml
> +
Only one new line is required at the end of file.

2017-06-12 13:05 UTC, devanshutechracers commented on swagger.yaml
> +          $ref: "#/definitions/Owner"
is this `schema ref` or `example`?

2017-06-12 13:07 UTC, devanshutechracers commented on swagger.yaml
> +          $ref: "#/definitions/Owner"
did you do the self review before submission.

2017-06-12 13:08 UTC, devanshutechracers commented on swagger.yaml
> +        example:
is this `schema ref` or `example`?

2017-06-12 13:13 UTC, ketanTechracers commented
@ayushttiwari  _Google Search_ API ?? I thought it was Github's API. Check before you raise Pull request!

2017-06-12 13:13 UTC, devanshutechracers commented on swagger.yaml
> +- "http"
http !!!!!!!!!!!!!!!!!

2017-06-12 13:14 UTC, devanshutechracers commented on swagger.yaml
> +  Search repositories:
Is this a model?????

2017-06-12 13:18 UTC, devanshutechracers requested changes
- Add Google APIs in case of creating a pull request for GOOGLE SEARCH, not Github. 
- Read the API Documentation really carefully once again.

2017-06-12 13:20 UTC, devanshutechracers commented on swagger.yaml
> +      summary: "get all the film resources"
Copy + Paste should be done only when you can review all the things that you have copied.

2017-06-12 13:21 UTC, devanshutechracers requested changes
Incorrect Summary for APIs.

2017-06-12 14:11 UTC, ayushttiwari commented
Sorry sir,
For making so-many silly mistakes. Will review all your comments properly &
will try to solve my errors on my own. I will make it a point to review my
assignments on my own before making a pull request. Sorry again.

Ayush Tiwari

On Mon, Jun 12, 2017 at 6:51 PM, Devanshu Gupta <notifications@github.com>
wrote:

> *@devanshutechracers* requested changes on this pull request.
>
> Incorrect Summary for APIs.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ayushttiwari/node-assignments-training/pull/2#pullrequestreview-43433425>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/Ab5MH1JaH4OfCSLMEVRpfKQx6DDiEgpNks5sDTtWgaJpZM4N1lOY>
> .
>

2017-06-17 10:36 UTC, ketanTechracers commented
Why is this PR having app.js and node_modules ?? It is supposed to be a swagger doc assignment PR. re-raise another pull request with just the swagger assignment!

2017-06-17 10:36 UTC, closed without merging