callback basics assignment
ayushttiwari/node-assignments-training pull request #4
Opened 2017-06-13 14:11 UTC by ayushttiwari

2017-06-13 14:24 UTC, devanshutechracers requested changes
Files to run the code are missing.

2017-06-13 18:49 UTC, rockon1985 reviewed
Correct indentation and improve nomenclature

2017-06-13 18:49 UTC, ketanTechracers commented on assignment4.js
> +	if(i<5) {
there should be a space before and after an operator in JS. Eg: `a + b` instead of `a+b`

2017-06-13 18:49 UTC, ketanTechracers commented on assignment4.js
> +	if(i<5) {
there should be a space before and after an operator in JS. eg `a + b` instead of `a+b`

2017-06-13 18:49 UTC, ketanTechracers commented on assignment4.js
> +function callBackExample(file){
rename the method to something meaningful like readFiles or something

2017-06-13 18:49 UTC, ketanTechracers commented on assignment4.js
> +callBackExample(files);
add a new line at the end of each file

2017-06-13 18:49 UTC, ketanTechracers commented on assignment4.js
> +	  return console.log(err);
correct indentation in this file. Required indentation: two spaces

2017-06-13 18:49 UTC, ketanTechracers commented on assignment4.js
> +function callBackExample(file){
> file parameter name seems as if its a single file, but it's actually a list of files. Rename the parameter accordingly

2017-06-13 19:23 UTC, rockon1985 approved these changes

2017-06-13 20:29 UTC, devanshutechracers commented on assignment4.js
> +let files = ["./f1","./f2","./f3", "./f4", "./f5"], i = 0;
what is `i`, could this be elaborate name?

2017-06-13 20:30 UTC, devanshutechracers commented on assignment4.js
> +fs = require('fs');
`fs` should be defined. using global namespace is not supported by all NodeJS version.

2017-06-13 20:34 UTC, devanshutechracers commented on assignment4.js
> +function fileReader(file){
There should be a space between starting the function and the curly braces.

2017-06-13 20:40 UTC, devanshutechracers commented on assignment4.js
> +    return console.log(err);
indentation from line 6-13 is messed up

2017-06-13 20:42 UTC, devanshutechracers commented on assignment4.js
> +  fs.readFile(fileList[i], 'utf8' , function (err,data) {
there should only be a space after comma, not before while calling a function

2017-06-13 20:43 UTC, devanshutechracers commented on assignment4.js
> +fs = require('fs');
All the import should be done in the first line.

2017-06-13 20:43 UTC, devanshutechracers commented on assignment4.js
> +fileReader(files);
line break after finishing a function.

2017-06-13 20:45 UTC, devanshutechracers commented on assignment4.js
> +  fs.readFile(fileList[i], 'utf8' , function (err,data) {
What is `fileList`? This is a Runtime Error, did you run the code before submission.

2017-06-13 20:46 UTC, devanshutechracers requested changes
Runtime Error. Please run your code before submission.

2017-06-15 11:43 UTC, devanshutechracers commented on assignment4.js
> +fileReader(files);
EOF should contain New Line.

2017-06-15 11:43 UTC, devanshutechracers commented on assignment4.js
> +  fs.readFile(fileList[fileNo], 'utf8', function (err,data) {
space after `,` is required.

2017-06-15 11:45 UTC, devanshutechracers commented on assignment4.js
> +const files = ["./f1","./f2","./f3", "./f4", "./f5"];
Line break should be added after requires

2017-06-15 11:48 UTC, devanshutechracers commented on assignment4.js
> +function fileReader(fileList) {
Line break before function would increase readability.

2017-06-15 11:48 UTC, devanshutechracers requested changes
Add Line Breaks and space to improve readability.

2017-06-15 14:24 UTC, devanshutechracers approved these changes
Approved.

2017-06-15 14:27 UTC, rockon1985 approved these changes

2017-06-15 14:29 UTC, merged

2017-06-15 14:29 UTC, ketanTechracers commented
Finally satisfied with the code! Merging it!